#!/bin/bash

export SXHKD_SHELL=bash

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 4
bspc config top_padding 0
bspc config bottom_padding 0
bspc config window_gap 0
bspc config normal_border_color "#1d2021"
bspc config focused_border_color "#fb4934"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config pointer_modifier mod4

# Start a new terminal from which to run sxhkd
alacritty &
disown
